### ISSUE TITLE
stack can't use cabal-install-2.0 or newer as a solver

### ISSUE THREAD

**Issue by sjakobi** [harendra-kumar/packcheck#10]
[Log](https://travis-ci.org/sjakobi/bsb-http-chunked/jobs/355584876#L884)

I'm not sure whether it's worth hardcoding that stack should install v1.24.

**Comment by harendra-kumar** [comment]
Now you can specify cabal-install-1.24 in the apt sources and it will pick up that one automatically.

**Comment by sjakobi** [comment]
Thanks a lot, @harendra-kumar! :)
