### ISSUE TITLE
running packcheck a minimal complete "hello world" Haskell on NixOS

### ISSUE THREAD

**Issue by p-alik** [harendra-kumar/packcheck#5]
[Haskell Weekly Issue 90](https://haskellweekly.news/issues/90.html) introduces a new Haskell "Hello World" project with full CI integration of [AppVeyor](https://ci.appveyor.com/project/harendra-kumar/packcheck) and [Travis](https://travis-ci.org/).

With regard to the [README](https://github.com/harendra-kumar/packcheck) the project provides a bash script `packcheck.sh`, which could be used for running purpose in local environment also.

The first attempt on `NixOS` 17.09 failed.
```
$ ./packcheck.sh 
bash: ./packcheck.sh: /bin/bash: bad interpreter: No such file or directory
```

As reported in [#3](https://github.com/harendra-kumar/packcheck/issues/3) static `/bin/bash` in shebang doesn't work in particular environments. (For instance `FreeBSD` also).

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@palik/running-packcheck-a-minimal-complete-hello-world-haskell-on-nixos">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by harendra-kumar** [comment]
PR #4 merged to address this. BTW, I am not a NixOS/BSD user, this was mainly tested on Linux/Mac/Windows. The change that you made in #4 will work much more widely. Thanks for the contribution.
