### ISSUE TITLE
`cabal install` doesn't install build-tool-depends

### ISSUE THREAD

**Issue by sjakobi** [harendra-kumar/packcheck#8]
I noticed this issue when I added a dependency on `pretty-show` which lists `happy` in its `build-tool-depends`. [Travis log](https://travis-ci.org/sjakobi/bsb-http-chunked/jobs/354480770#L803).

AFAIK `cabal new-install` does install `build-tool-depends` so maybe you could make packcheck use new-style cabal when the cabal version is sufficiently recent?

**Comment by harendra-kumar** [comment]
I am not much familiar with `cabal`, there may be an option that I need to use to make it install build-tool-depends. Let me check.

Just today, I was wondering whether I should add the new-style cabal build support as well. But it will take some time, because I need to understand it first. Whenever I have some time, I will try.

**Comment by sjakobi** [comment]
haskell-CI [uses new-style cabal](https://github.com/haskell-CI/haskell-ci/blob/master/.travis.yml), so maybe you could adapt some tricks from there.

**Comment by harendra-kumar** [comment]
@sjakobi you can try the `packcheck.sh cabal-new` build type. I used the `cabal new-build` but I did not use the `cabal new-install` command yet. Not sure if your problem will get solved with this.

**Comment by sjakobi** [comment]
@harendra-kumar Thanks for working on this! :)

There is a problem with the  command `cabal new-build --enable-tests --enable-benchmarks --ghc-options="-Werror"`: Because cabal new-build applies the ghc option also to the dependencies, it reinstalls them and fails because many of them are not warning-free.

[Log](https://travis-ci.org/sjakobi/bsb-http-chunked/jobs/355058908#L923)

**Comment by harendra-kumar** [comment]
Yes, I noticed that and removed `-Werror` from global options in the default CI configs. You can use it for stack builds if you want by just saying `GHC_OPTIONS=-Werror` in the env line.

**Comment by sjakobi** [comment]
Another issue is that `cabal new-test` fails, when there are no buildable tests. [Log](https://travis-ci.org/sjakobi/bsb-http-chunked/jobs/355066011).

**Comment by harendra-kumar** [comment]
When I completely remove the test stanza from the cabal file I see this one:

```
cabal new-test
cabal: Distribution/Client/TargetSelector.hs:(355,7)-(356,55): Irrefutable pattern failed for pattern t' : _
```

It seems its not very well tested yet.

**Comment by sjakobi** [comment]
What version of cabal is that?

**Comment by harendra-kumar** [comment]
```
cabal-install version 2.0.0.1
compiled using version 2.0.1.1 of the Cabal library 
```

**Comment by harendra-kumar** [comment]
Perhaps need 2.2

**Comment by harendra-kumar** [comment]
@sjakobi you can try the new version of `packcheck` passing `DISABLE_TEST=y` in env.

**Comment by sjakobi** [comment]
Thanks, that's a good workaround.

Strangely a few of my jobs still fail, but I don't see why. Can you take a look:

https://travis-ci.org/sjakobi/bsb-http-chunked/jobs/355085654

**Comment by harendra-kumar** [comment]
Ah, shell! This is because `test "$DISABLE_TEST" && ...` results in an exit code of 1 and travis does not like that. Let me fix this.

**Comment by harendra-kumar** [comment]
@sjakobi can you try again now?

**Comment by sjakobi** [comment]
All green! Thanks a lot @harendra-kumar! :)
